plugins/genevagui/.classpath, plugins/genevagui/src/com/ibm/safr/we/ui/editors/ImportUtilityEditor.java
=> replace Focus listeners with selection listeners

plugins/genevagui/src/com/ibm/safr/we/constants/Codes.java, plugins/genevagui/src/com/ibm/safr/we/constants/UserPreferencesNodes.java, plugins/genevagui/src/com/ibm/safr/we/model/LookupPath.java, plugins/genevagui/src/com/ibm/safr/we/ui/editors/LookupPathEditor.java, plugins/genevagui/src/com/ibm/safr/we/ui/editors/SAFREditorPart.java, plugins/genevagui/src/com/ibm/safr/we/ui/editors/pf/PhysicalFileGeneralEditor.java, plugins/genevagui/src/com/ibm/safr/we/ui/utilities/UIUtilities.java
=> Updates from SAFR

plugins/genevagui/src/com/ibm/safr/we/internal/data/pgdao/PGLookupDAO.java
=> delete a lookup

plugins/genevagui/src/com/ibm/safr/we/ui/editors/batchview/ActivateViewsViews.java
Signed-off-by: hammyau <blueham60@gmail.com>
=> filter null page

plugins/genevagui/src/com/ibm/safr/we/constants/Codes.java, plugins/genevagui/src/com/ibm/safr/we/model/LookupPath.java
=> sync from SAFR

plugins/genevagui/src/com/ibm/safr/we/model/SAFRValidator.java
=> alnum < 32767

docs/_config.yml, docs/_sass/color_schemes/geneva.scss
Signed-off-by: emorrow38 <emorrow@au1.ibm.com>
=> EM-Colors-02

docs/_config.yml
Signed-off-by: emorrow38 <emorrow@au1.ibm.com>
=> EM-Fix-GHPages-04

NOTICE
=> add EPL1.0 license text into NOTICE

build.sh
=> Move Grammar Location

README.md, build.sh, prebuild/grammar.sh
added the pre and post script for custom execution.  Also updated the readme with these new parameters.
=> BuildGrammerParm

postbuild/postbuild.sh
=> change MV to CP for JRE

postbuild/postbuild.sh
=> Minor JRE Change

build.sh, prebuild/RCG.sh, prebuild/grammar.sh
This will pick up the change to build.sh, and the new rcg.sh.  It also has the change to grammar.sh from main merged in.
=> Rcgbuild to merge into rcginterface

README.md
Updated the last steps for use of postgres to make connection manager parameters clearer.
=> Update to Readme for Postgres

build.sh
Had "generator" in build script, not "app".
=> One word change

README.md, docs/ProduceRelease.md
=> Readme-and-Procedure

prebuild/RCA.sh
Added GERS-JARS test in the WB RCA.sh build script to install DB2 Jars if desginated.
=> Build-correction

README.md, build.sh, ccb2lr/pom.xml, prebuild/RunControlApps.sh
updated script names and readme variable and ccb2lr pom version.
=> Rcg install

plugins/genevagui/META-INF/MANIFEST.MF, plugins/genevagui/src/com/ibm/safr/we/ui/editors/view/ViewEditor.java, postbuild/postbuild.sh, prebuild/configBuild.sh, prebuild/rcappsVersionFromTo.sh
Changes to pickup the RCApps 1.1.0_RC1
=> Post build fix

plugins/genevagui/src/com/ibm/safr/we/model/utilities/BatchActivateViews.java, plugins/genevagui/src/com/ibm/safr/we/model/view/View.java, plugins/genevagui/src/com/ibm/safr/we/ui/editors/batchview/ActivateViewsError.java, products/com.ibm.safr.we.product/com.ibm.safr.we.rcp.product
=> RC2 Iteration

database/db2/GVBQINCO.DDL, database/postgres/populateCode.sql, plugins/genevagui/.project
=> Code table update1

plugins/genevagui/src/com/ibm/safr/we/ui/utilities/SAFRDialogCellEditor.java
=> License Fix

postbuild/pom.xml
=> Make JRE Optional
